"""Render assets/*.svg and README.md from profile.toml and the site's articles.

make            # or: uv run --no-project --with fonttools --with brotli tools/build.py
"""

from __future__ import annotations

import datetime as dt
import html
import re
import subprocess
import tomllib
from collections.abc import Callable
from pathlib import Path

import metrics
import panels
from svg import Doc
from theme import THEMES

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
DESK_COUNT = 3
CARD = re.compile(r'card-eyebrow">([^<]+)</p><h2><a href="(/\d{4}-[^"]+)">([^<]+)</a></h2><time datetime="([\d-]+)"')


def fetch(url: str) -> bytes:
    """GET with curl, which negotiates the site's TLS where urllib cannot."""
    return subprocess.run(["curl", "-fsSL", url], check=True, capture_output=True).stdout  # noqa: S603, S607


def articles(site: str) -> list[dict]:
    """The latest English articles, parsed from the site's /articles/ index."""
    text = fetch(f"{site}/articles/").decode()
    rows = sorted({(m[3], m[1], m[2], m[0]) for m in CARD.findall(text)}, reverse=True)
    if len(rows) < DESK_COUNT:
        raise SystemExit("articles: too few cards parsed from /articles/; has the markup changed?")
    return [
        {
            "title": html.unescape(title),
            "topic": html.unescape(topic).upper(),
            "date": f"{dt.date.fromisoformat(day):%-d %B %Y}",
            "url": f"{site}{path}",
        }
        for day, path, title, topic in rows[:DESK_COUNT]
    ]


def jobs(cfg: dict, latest: list[dict], stats: list[dict]) -> dict[str, Callable[[dict], Doc]]:
    """Every asset name mapped to the panel that draws it for a theme."""
    out: dict[str, Callable[[dict], Doc]] = {
        "hero": lambda t: panels.hero(t, cfg["hero"]),
        "numbers": lambda t: panels.numbers(t, {**cfg["numbers"], "stats": stats}),
        "paper": lambda t: panels.paper(t, cfg["paper"]),
        "desk": lambda t: panels.header(t, "Latest", "From the desk."),
        "finale": lambda t: panels.finale(t, cfg["finale"]),
    }
    for n, p in enumerate(cfg["pillars"], 1):
        out[f"section-{p['key']}"] = lambda t, p=p, n=n: panels.section(t, p, n)
        for r in p["repos"]:
            out[f"card-{r['name']}"] = lambda t, r=r: panels.card(t, r)
    for n, a in enumerate(latest, 1):
        out[f"article-{n}"] = lambda t, a=a: panels.article(t, a)
    return out


def render(todo: dict[str, Callable[[dict], Doc]]) -> dict[str, str]:
    """Write every panel in both themes; return name -> alt text."""
    alts = {}
    for name, draw in todo.items():
        for mode, theme in THEMES.items():
            doc = draw(theme)
            (ASSETS / f"{name}-{mode}.svg").write_text(doc.render())
        alts[name] = doc.title
    return alts


def pic(name: str, alt: str, url: str | None = None, width: str = "100%", base: str = "assets") -> str:
    img = (
        f'<picture><source media="(prefers-color-scheme: dark)" srcset="{base}/{name}-dark.svg">'
        f'<img src="{base}/{name}-light.svg" width="{width}" alt="{html.escape(alt)}"></picture>'
    )
    return f'<a href="{url}">{img}</a>' if url else img


def page(cfg: dict, alts: dict[str, str], latest: list[dict]) -> str:
    gh, site = cfg["github"], cfg["site"]
    links = " &nbsp;·&nbsp; ".join(f'<a href="{x["url"]}">{x["label"]}</a>' for x in cfg["finale"]["links"])
    out = [
        "<!-- Generated by tools/build.py from profile.toml. Edit those, not this file. -->",
        # The hero is served live by the profile-clock Worker, which sets the
        # clock to London time; the committed assets/hero-*.svg are its source
        # and the static fallback it redirects to.
        pic("hero", alts["hero"], site, base=cfg.get("clock", "assets")),
        f'<p align="center">{links}</p>',
        pic("numbers", alts["numbers"]),
    ]
    for p in cfg["pillars"]:
        cards = [pic(f"card-{r['name']}", alts[f"card-{r['name']}"], f"{gh}/{r['name']}", "49%") for r in p["repos"]]
        out += [
            pic(f"section-{p['key']}", alts[f"section-{p['key']}"]),
            "<p>\n" + "\n".join(cards) + "\n</p>",
            f'<p align="right"><a href="{p["more"]}">Learn more about {p["eyebrow"]} ›</a></p>',
        ]
    desk = [pic(f"article-{n}", alts[f"article-{n}"], a["url"], "32.6%") for n, a in enumerate(latest, 1)]
    out += [
        pic("paper", alts["paper"], cfg["paper"]["url"]),
        pic("desk", alts["desk"]),
        "<p>\n" + "\n".join(desk) + "\n</p>",
        f'<p align="right"><a href="{site}/articles/">See all articles ›</a></p>',
        pic("finale", alts["finale"], f"{site}/contact/"),
        f'<p align="center"><sub>Built from <a href="profile.toml">profile.toml</a> in the typefaces'
        f' and colours of <a href="{site}">sebastienrousseau.com</a>.</sub></p>',
    ]
    return "\n\n".join(out) + "\n"


def main() -> None:
    cfg = tomllib.loads((ROOT / "profile.toml").read_text())
    latest = articles(cfg["site"])
    stats = metrics.collect()
    ASSETS.mkdir(exist_ok=True)
    alts = render(jobs(cfg, latest, stats))
    (ROOT / "README.md").write_text(page(cfg, alts, latest))


if __name__ == "__main__":
    main()
